# Generated by Django 5.1.6 on 2025-02-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_hotel', to='hotel.hotel'),
        ),
    ]
