# Generated by Django 5.1.6 on 2025-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
