# Generated by Django 5.1.6 on 2025-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancel_booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='go_in',
            field=models.DateField(),
        ),
    ]
