# Generated by Django 5.1.6 on 2025-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_country_city_name_en_country_city_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
