# Generated by Django 5.1.6 on 2025-02-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_country_country_users_alter_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_users',
        ),
        migrations.AddField(
            model_name='rating',
            name='country_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.country'),
        ),
    ]
