# Generated by Django 5.1.6 on 2025-02-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_country_country_users_rating_country_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='country_rating',
        ),
        migrations.AddField(
            model_name='country',
            name='country_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
